services:
  graphql:
    restart: always
    build:
      context: ./graphql
    depends_on:
      - postgres
    ports:
      - 5433:5433
    command:
      - "--connection"
      - "postgres://postgres:${POSTGRES_PASSWORD:-password}@postgres:5432/postgres?sslmode=disable"
      - "--port"
      - "5433"
      - "--schema"
      - "mergestat,sqlq,public"
      - "--append-plugins"
      - "@graphile-contrib/pg-simplify-inflector,postgraphile-plugin-connection-filter,/graphql/container-sync-jobs/index.js,/graphql/exec-sql/index.js,/graphql/service-credentials/index.js"
      - "-o"
      - "--subscriptions"
      - "--watch"
      - "--dynamic-json"
      - "--no-setof-functions-contain-nulls"
      - "--no-ignore-rbac"
      - "--show-error-stack=json"
      - "--extended-errors=hint,detail,errcode"
      - "--enhance-graphiql"
      - "--allow-explain"
      - "--enable-query-batching"
      - "--legacy-relations=omit"
      - "--jwt-secret=${JWT_SECRET:-secret}"
      - "--default-role=mergestat_anonymous"
    environment:
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET:-password}
      DISPLAY_PG_HOSTNAME: localhost
      DISPLAY_PG_PORT: 5432
      DISPLAY_PG_DATABASE: postgres
      DISPLAY_PG_USER: postgres
